name: build
on: push

jobs:
  build-non-windows-image:
    name: 'Build Non-Windows Image'
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [ ubuntu-latest, macos-latest ]
        gu-binary: [ gu.cmd ]
        exclude:
          - os: ubuntu-latest
            gu-binary: gu.cmd
          - os: macos-latest
            gu-binary: gu.cmd
    steps:
      - name: 'Checkout'
        uses: actions/checkout@v2
      - name: Setup Graalvm
        id: setup-graalvm
        uses: DeLaGuardo/setup-graalvm@master
        with:
          graalvm: '21.2.0'
          java: 'java11'
          arch: 'amd64'
      - name: Install native-image component
        run: |
          ${{ matrix.gu-binary }} install native-image
      - name: 'Build Native Image'
        run: |
          ./gradlew nativeCompile

      - name: 'Publish Native Image'
        if: success()
        uses: actions/upload-artifact@v2-preview
        with:
          name: 'authlib-patcher-${{matrix.label}}'
          path: 'build/native/nativeCompile/authlib-patcher-lib'

  build-windows-image:
    name: 'Build Windows Image'
    runs-on: windows-latest

    steps:
      - name: 'Checkout'
        uses: actions/checkout@v1

      - name: Setup Graalvm
        id: setup-graalvm
        uses: DeLaGuardo/setup-graalvm@master
        with:
          graalvm: '21.0.0.2'
          java: 'java11'
          arch: 'amd64'

      - name: Install native-image component
        run: |
          gu install native-image

      - name: 'Set up Visual C Build Tools Workload for Visual Studio 2017 Build Tools'
        run: |
          choco install visualstudio2017-workload-vctools

      - name: 'Build Native Image'
        shell: cmd
        run: |
          call "C:\Program Files (x86)\Microsoft Visual Studio\2017\BuildTools\VC\Auxiliary\Build\vcvars64.bat"
          gradlew.bat nativeCompile

      - name: 'Publish Windows Image'
        if: success()
        uses: actions/upload-artifact@v2-preview
        with:
          name: 'authlib-patcher-lib-windows.exe'
          path: 'build/native/nativeCompile/authlib-patcher-lib.exe'